/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Cats example
 * The cats API description
 * OpenAPI spec version: 1.0
 */

export interface AddToCartDto {
  userId: number;
  productId: number;
  quantity?: number;
}
