/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Cats example
 * The cats API description
 * OpenAPI spec version: 1.0
 */

export type CartControllerClearCartParams = {
  /**
   * User ID whose cart should be cleared
   */
  userId: number;
};
