/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Cats example
 * The cats API description
 * OpenAPI spec version: 1.0
 */
import type { CartItemDto } from './cartItemDto';

export interface CartResponseDto {
  id: number;
  userId: number;
  items: CartItemDto[];
  total: number;
  itemsCount: number;
}
