/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Cats example
 * The cats API description
 * OpenAPI spec version: 1.0
 */
import type { ProductResponseDto } from './productResponseDto';

export interface ProductListResponseDto {
  products: ProductResponseDto[];
  count: number;
}
