/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Cats example
 * The cats API description
 * OpenAPI spec version: 1.0
 */

export type ProductControllerFindAllParams = {
  /**
   * Number of records to skip
   */
  skip?: number;
  /**
   * Number of records to take
   */
  take?: number;
  /**
   * Search term to filter products by name or description
   */
  search?: string;
  /**
   * Sorting criteria as JSON string
   */
  orderBy?: string;
};
